### ISSUE TITLE
Unexpected warning when calling ld_search

### ISSUE THREAD

**Issue by ramiromagno** [ropensci/rsnps#34]
`ld_search("rs6004658", dataset = "onekgpilot", panel = "CEU", quiet = FALSE)`

yields:

```
Warning message:
In if (grepl("NCBI", deparse(sys.call()))) { :
  the condition has length > 1 and only the first element will be used
```

It seems this always happens with `ld_search` calls that include 3 or more named parameters.

**Comment by haozhu233** [comment]
Hi, @ramiromagno, can you provide a little more details on how you encountered this bug? Also, can you make sure you are using the most recent version of this package?

**Comment by ramiromagno** [comment]
`> packageVersion("rsnps")
[1] ‘0.2.0.9000’`

**Comment by ramiromagno** [comment]
@haozhu233 : the context is simply issueing: `ld_search("rs6004658", dataset = "onekgpilot", panel = "CEU", quiet = FALSE)`

**Comment by haozhu233** [comment]
@ramiromagno Can you try the latest github version? I found this problem is fixed in the most recent version of this package. 
```devtools::install_github("ropensci/rsnps")```

**Comment by ramiromagno** [comment]
I am using the latest version. 

I've just forced install with devtools the package. I restart the R session, and the errors prevail when:

`ld_search("rs10510102", dataset = "onekgpilot", panel = "CEU", RSquaredLimit = 0.4,
          distanceLimit = 500, GeneCruiser = FALSE, quiet = FALSE)`

I still get: 

`> library(rsnps)
> ld_search("rs10510102", dataset = "onekgpilot", panel = "CEU", RSquaredLimit = 0.4,
+           distanceLimit = 500, GeneCruiser = FALSE, quiet = FALSE)
Querying SNAP...
Querying NCBI for up-to-date SNP annotation information...
Error in stats::setNames(lapply(tmpsplit, parse_data), SNPs) : 
  'names' attribute [193] must be the same length as the vector [189]
In addition: Warning message:
In if (grepl("NCBI", deparse(sys.call()))) { :
  the condition has length > 1 and only the first element will be used`.

`> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rsnps_0.2.0.9000

loaded via a namespace (and not attached):
 [1] httr_1.2.1    magrittr_1.5  plyr_1.8.4    R6_2.2.0      tools_3.3.0  
 [6] curl_2.3      Rcpp_0.12.8   stringi_1.1.2 stringr_1.1.0 XML_3.98-1.5 
> `

**Comment by ramiromagno** [comment]
@haozhu233 : you do not reproduce this warning and error?

**Comment by haozhu233** [comment]
@ramiromagno I just reproduced this error. Now I'm trying to see what happened

**Comment by sckott** [comment]
thanks for being on top of this @haozhu233 - let me know if you need an extra eye

**Comment by haozhu233** [comment]
@ramiromagno Can you try to reinstall the dev version now? I think I fixed the bug by https://github.com/ropensci/rsnps/commit/39d0dc310faab7aaef91a329dea913ab79df97f3. Don't worry about the "the condition has length > 1" message. Even though I haven't figured out why it happened, the related codes are only for displaying messages about deprecated codes

@sckott This is actually a problem with `ncbi_snp_query2()`. `ld_search` calls `ncbi_snp_query2` for some proxy SNPs. The sample codes @ramiromagno provides generated some proxy SNPs that don't exist. I added some codes to increase the stability of `ncbi_snp_query2()` and a warning message to show the names of the SNPs that returns NULL results while fetching

**Comment by ramiromagno** [comment]
@haozhu233 Yup, it is indeed fixed now. Thank you so much for that! However, a message such as

```
Warning messages:
1: In if (grepl("LDSearch", deparse(sys.call()))) { :
  the condition has length > 1 and only the first element will be used
2: In ncbi_snp_query2(proxy_SNPs) :
  Query results from SNPs rs78368090, rs117060241, rs76872398, rs118049432, rs117248423 are empty.
```

might be a too cryptic to most users who might be confused to see another function (`ncbi_snp_query2`) surfacing in the warnings. Maybe adding some more explanation to `ld_search` help page in the Details section would help...

Anyway, you may close this issue.

**Comment by Sandyyy123** [comment]
The LD search command was working perfectly until yesterday. I am having the following issue now: 
Error in split_to_df(tmp, sep = "\t", fixed = TRUE) : 
  non-equal lengths for each entry of x post-splitting
In addition: Warning message:
In if (grepl("NCBI", deparse(sys.call()))) { :
  the condition has length > 1 and only the first element will be used
